blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.gg/your-community-link
    about: Join our Discord community for quick help and discussions
  - name: Documentation
    url: https://your-github-username.github.io/astrobot/
    about: Check our documentation for guides and answers to common questions